apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "name" . }}
  namespace: {{ template "namespace" . }}
spec:
  selector:
    matchLabels:
      k8s-app: {{ template "name" . }}
  template:
    metadata:
      labels:
        k8s-app: {{ template "name" . }}
    spec:
      hostNetwork: true
      containers:
      - name: {{ template "name" . }}
        image: {{ .Values.image }}
        args:
          # The masq-chain must be IP-MASQ
          - --masq-chain=IP-MASQ
          # To non-masquerade reserved IP ranges by default,
          # uncomment the following line.
          # - --nomasq-all-reserved-ranges
        securityContext:
          privileged: false
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        volumeMounts:
          - name: config
            mountPath: /etc/config
      volumes:
        - name: config
          configMap:
            # Note this ConfigMap must be created in the same namespace as the daemon pods - this spec uses kube-system
            name: {{ template "name" . }}
            optional: true
            items:
              # The daemon looks for its config in a YAML file at /etc/config/ip-masq-agent
              - key: config
                path: {{ template "name" . }}
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - key: "CriticalAddonsOnly"
        operator: "Exists"

