{{- $context := printf "%s@%s:%s" .Values.user .Values.cluster .Values.namespace }}
###
#
# begin: kubeconfig
#
apiVersion: v1
kind: Config
clusters:
  - name: {{ .Values.cluster }}
    cluster:
      server: {{ .Values.server }}
      certificate-authority-data: {{ .Values.cert }}
contexts:
  - name: {{ $context }}
    context:
      cluster: {{ .Values.cluster }}
      namespace: {{ .Values.namespace }}
      user: {{ .Values.user }}
current-context: {{ $context }}
users:
  - name: {{ .Values.user }}
    user:
    {{- if .Values.token }}
      token: {{ .Values.token }}
    {{- else }}
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        command: aws
        args:
          - "eks"
          - "get-token"
          - "--cluster-name"
          - "{{ .Values.cluster }}"
    {{- end }}
#
# end: kubeconfig
#
###
