apiVersion: v1
kind: Secret
metadata:
  name: {{ template "name" . }}
  namespace: {{ template "namespace" . }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.crt | b64enc }}
  tls.key: {{ .Values.key | b64enc }}
