image:
  name: foo/bar:1.0.0
port: 8080

ingress:
  host: foo.bar.com

nodeSelector:
  label-1: foo
  label-2: bar

tolerations:
  - key: pool
    value: blue
    effect: NoExecute

sideCar:
  image:
    name: side/side:1.0.0
    # pullPolicy: Always
  # livenessProbe:
  #   isHttpGet: true
  #   httpGet:
  #     path: /
