{{- if .Values.microsegmentation }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: twistlock-configmap-updater-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.configmap_role_name }}
subjects:
- apiGroup: 
  kind: ServiceAccount
  name: twistlock-service
  namespace: {{ .Values.namespace }}
{{- end}}