apiVersion: v1
kind: Secret
metadata:
  name: twistlock-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  service-parameter: {{ .Values.service_parameter }}
  ca.pem: {{ .Values.ca_cert }}
  client-cert.pem: {{ .Values.client_cert }}
  client-key.pem: {{ .Values.client_key }}
  admission-cert.pem: {{ .Values.admission_cert }}
  admission-key.pem: {{ .Values.admission_key }}
{{if .Values.access_ca}}
  access-ca.pem: {{ .Values.access_ca }}
{{- end}}