apiVersion: v1
kind: ServiceAccount # Service Account is used for managing security context constraints policies in Openshift (SCC)
metadata:
  name: twistlock-service
  namespace: {{ .Values.namespace }}
secrets:
- name: twistlock-secrets