{{- $name := include "name" . -}}

apiVersion: {{ template "deploymentApiVersion" . }}
kind: Deployment
metadata:
  namespace: {{ template "namespace" . }}
  name: {{ $name }}
  annotations:
    {{- range $key, $value := .Values.metadataAnnotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
      annotations:
        {{- range $key, $value := .Values.specTemplateMetadataAnnotations }}
          {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      {{- if .Values.securityContext }}
      securityContext:
        {{- .Values.securityContext | toYaml | trim | nindent 8 }}
      {{- end }}
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- .Values.nodeSelector | toYaml | trim | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- .Values.tolerations | toYaml | trim | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $name }}
          image: {{ .Values.image.name }}
          {{- if .Values.volumeMounts }}
          volumeMounts:
            {{- .Values.volumeMounts | toYaml | trim | nindent 12 }}
          {{- end}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command:
            {{- range .Values.command }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- .Values.resources | toYaml | trim | nindent 12 }}
          {{- end }}
          {{- if .Values.port }}
          ports:
            - containerPort: {{ template "containerPort" . }}
            {{- if .Values.portAdd }}
            - containerPort: {{ template "containerPortAdd" . }}
            {{- end }}
          {{- end }} {{- /* if Values.port */}}

          {{- include "probe" (dict "ctx" . "cfg" .Values.readinessProbe "type" "readiness") | trim | nindent 10 }}
          {{- include "probe" (dict "ctx" . "cfg" .Values.livenessProbe "type" "liveness") | trim | nindent 10 }}

          {{- if .Values.env }}
          env:
            {{- range $key, $value := .Values.env }}
              - name: {{ $key }}
              {{- if eq (kindOf $value) "map" }}
                {{- $value | toYaml | trim | nindent 16 }}
              {{- else }}
                value: {{ $value | quote }}
              {{- end }}
            {{- end }}
          {{- end }}

        {{- if .Values.sideCar }}
        {{ with .Values.sideCar }}
        - name: {{ $name }}-side-car
          image: {{ .image.name }}
          {{- if .volumeMounts }}
          volumeMounts:
            {{- .volumeMounts | toYaml | trim | nindent 12 }}
          {{- end}}
          {{- if .image.pullPolicy }}
          imagePullPolicy: {{ .image.pullPolicy }}
          {{- end }}
          {{- if .command }}
          command:
            {{- range .command }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- if .resources }}
          resources:
            {{- .resources | toYaml | trim | nindent 12 }}
          {{- end }}
          {{- if .port }}
          ports:
            - containerPort: {{ template "containerPort" . }}
            {{- if .portAdd }}
            - containerPort: {{ template "containerPortAdd" . }}
            {{- end }}
          {{- end }} {{- /* if .port */}}

          {{- include "probe" (dict "ctx" . "cfg" .readinessProbe "type" "readiness") | trim | nindent 10 }}
          {{- include "probe" (dict "ctx" . "cfg" .livenessProbe "type" "liveness") | trim | nindent 10 }}

          {{- if .env }}
          env:
            {{- range $key, $value := .env }}
              - name: {{ $key }}
              {{- if eq (kindOf $value) "map" }}
                {{- $value | toYaml | trim | nindent 16 }}
              {{- else }}
                value: {{ $value | quote }}
              {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
        {{- end }}

      {{- if .Values.volumes }}
      volumes:
        {{- .Values.volumes | toYaml | trim | nindent 8 }}
      {{- end }}
