{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ template "namespace" . }}
  name: {{ template "name" . }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "name" . }}
                port:
                  number: {{ .Values.port }}
    {{- if .Values.ingress.add }}
    - host: {{ .Values.ingress.add }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "name" . }}
                port:
                  number: {{ or .Values.portAdd .Values.port }}
    {{- end }}
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      {{- if .Values.ingress.add }}
      - {{ .Values.ingress.add }}
      {{- end }}
      {{- if .Values.ingress.tlsSecret }}
      secretName: {{ .Values.ingress.tlsSecret }}
      {{- end -}}
{{- end -}}
