{{- if .Values.ingress.enabled -}}
{{- $hasV1Ingress := .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
{{- if .Values.ingress.apiVersion }}
apiVersion: {{ .Values.ingress.apiVersion }}
{{- else if $hasV1Ingress }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  namespace: {{ template "namespace" . }}
  name: {{ template "name" . }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            {{- if $hasV1Ingress }}
            pathType: Prefix
            backend:
              service:
                name: {{ template "name" . }}
                port:
                  number: {{ .Values.port }}
            {{- else }}
            backend:
              serviceName: {{ template "name" . }}
              servicePort: {{ .Values.port }}
            {{- end }}
    {{- if .Values.ingress.add }}
    - host: {{ .Values.ingress.add }}
      http:
        paths:
          - path: /
            {{- if $hasV1Ingress }}
            pathType: Prefix
            backend:
              service:
                name: {{ template "name" . }}
                port:
                  number: {{ or .Values.portAdd .Values.port }}
            {{- else }}
            backend:
              serviceName: {{ template "name" . }}
              servicePort: {{ or .Values.portAdd .Values.port }}
            {{- end }}
    {{- end }}
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      {{- if .Values.ingress.add }}
      - {{ .Values.ingress.add }}
      {{- end }}
      {{- if .Values.ingress.tlsSecret }}
      secretName: {{ .Values.ingress.tlsSecret }}
      {{- end -}}
{{- end -}}
