{{- if and .Values.pdb.enabled (gt (int .Values.replicas) 1) -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "name" . }}
  namespace: {{ template "namespace" . }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
{{- end -}}
