{{- if .Values.secretData -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "name" . }}
  namespace: {{ template "namespace" . }}
data:
  {{- range $key, $value := .Values.secretData }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end -}}
