{{- if .Values.secretData -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "name" . }}
  namespace: {{ template "namespace" . }}
data:
  {{- .Values.secretData | toYaml | trim | nindent 2 }}
{{- end -}}
