{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ template "namespace" . }}
  name: {{ template "name" . }}
spec:
  ports:
    - name: main
      port: {{ .Values.port }}
    {{- if .Values.portAdd }}
    - name: add
      port: {{ .Values.portAdd}}
    {{- end }}
  selector:
    app: {{ template "name" . }}
{{- end -}}