apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-info
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
