apiVersion: v1
kind: Secret
metadata:
  namespace: {{ template "namespace" . }}
  name: {{ template "name" . }}
  {{- if .Values.annotations }}
  annotations:
  {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.labels }}
  labels:
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
type: Opaque
data:
{{- range $key, $value := .Values.data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
